/**
 * The queue's wire contract: what producers, consumers and admins exchange with a queue service.
 *
 * Expected queue conditions are discriminated results, never new RPC error codes - `full` and
 * `lease-lost` are a service answering a business question, and the global error vocabulary grows
 * only for conditions the protocol itself can produce. The public wrapper turns `full` into
 * QueueFullError; everything else it returns as data.
 *
 * This file is the contract that would split into its own package if a second backend ever
 * appears. Until then it lives here, and the split trigger is written down rather than hoped for.
 */

export interface WorkQueueCapacity {
    /** Ready tasks beyond this are refused `full` - reject-new only, never silent drop. */
    maxReadyTasks: number
    /** Estimated bytes of ready backlog. The estimate is conservative, not an accountant. */
    maxReadyBytes: number
    maxPayloadBytes: number
    maxHeaders?: number
    maxHeaderBytes?: number
}

export interface WorkQueueRetryPolicy {
    /** Deliveries, not re-deliveries: a task is dead-lettered after its maxAttempts-th failure. */
    maxAttempts: number
    /** Base delay before a failed task is offered again, growing exponentially per attempt. */
    delayMs: number
    maxDelayMs?: number
    /** 0..1: the fraction of the delay randomised away, so a herd of failures does not retry as one. */
    jitter?: number
}

/**
 * Context a task carries to its worker, per the adopted topology spec: `snapshot` is captured by
 * the producer at enqueue time and travels verbatim; `latest` names tokens to resolve when
 * execution starts - resolved by the worker against the source host's `$context`, so the task
 * runs under the world as it is, not as it was. An unresolvable `latest` fails the task rather
 * than running it context-blind.
 */
export type QueuedContext =
    | { mode: 'snapshot'; captured: unknown }
    | { mode: 'latest'; source: string; node?: string; tokenIds: readonly string[] }

/**
 * The authority generation a task was submitted under - the component authority fence from the
 * command-authority work, carried so a task is never silently executed under yesterday's grant.
 * The queue persists and delivers it; checking it against the live component is the worker's, and
 * the durable ownerEpoch variant arrives with the topology milestone.
 */
export interface TaskOwnerFence {
    peer: string
    namespace: string
    epoch: string
    generation: number
}

export interface EnqueueOptions {
    /** Generated by the wrapper when absent, and stable across that one call's internal retries. */
    taskId?: string
    /** Domain-level duplicate identity, retained for the queue's configured window. */
    deduplicationKey?: string
    /** Time from acceptance during which the task may *begin* - once leased, lease rules govern. */
    ttlMs?: number
    /** Higher first; FIFO within one priority. */
    priority?: number
    headers?: Readonly<Record<string, string>>
    context?: QueuedContext
    ownerFence?: TaskOwnerFence
}

export interface EnqueueReceipt {
    taskId: string
    acceptedAt: number
    /** True when this taskId or deduplication key was already accepted: the original receipt won. */
    duplicate: boolean
}

export interface EnqueueRequest<TTask> {
    taskId: string
    payload: TTask
    headers: Readonly<Record<string, string>>
    priority: number
    ttlMs?: number
    deduplicationKey?: string
    context?: QueuedContext
    ownerFence?: TaskOwnerFence
}

export type EnqueueResult = { status: 'accepted'; receipt: EnqueueReceipt } | { status: 'full'; retryAfterMs?: number }

/**
 * An acquire changes state and its response can be lost, so every request carries a stable
 * acquireId. Retried after an uncertain outcome, the same id returns the same lease rather than
 * leasing a second task to a consumer that only ever asked for one.
 */
export interface AcquireRequest {
    acquireId: string
    consumerId: string
    leaseMs: number
    waitMs: number
}

export interface WorkLease<TTask> {
    taskId: string
    /** Random and replaced on every lease. A mutation carrying an old token is `lease-lost`. */
    leaseToken: string
    payload: TTask
    headers: Readonly<Record<string, string>>
    /** Which delivery this is, starting at 1. */
    attempt: number
    leasedUntil: number
    context?: QueuedContext
    ownerFence?: TaskOwnerFence
}

export type AcquireResult<TTask> = { status: 'lease'; lease: WorkLease<TTask> } | { status: 'empty' }

export interface CompleteRequest {
    taskId: string
    leaseToken: string
    consumerId: string
}

export interface FailRequest {
    taskId: string
    leaseToken: string
    consumerId: string
    /** Bounded and sanitized by the service - never an unbounded stack or arbitrary object. */
    failure: string
}

export interface RenewRequest {
    taskId: string
    leaseToken: string
    consumerId: string
    extensionMs?: number
}

export type LeaseMutationResult =
    | { status: 'ok'; leasedUntil?: number }
    | { status: 'already-completed' }
    | { status: 'lease-lost' }
    | { status: 'not-found' }

export interface WorkQueueSnapshot {
    ready: number
    leased: number
    delayed: number
    deadLettered: number
    /** Cumulative: tasks whose TTL lapsed before any worker could begin them. */
    expired: number
    readyBytes: number
    oldestReadyAgeMs?: number
    saturated: boolean
    activeConsumers: number
}

export interface PageOptions {
    limit?: number
    /** The last taskId of the previous page. */
    after?: string
}

/** A dead letter's summary. The payload stays in the store; listing it wholesale would be a flood. */
export interface DeadLetterEntry {
    taskId: string
    headers: Readonly<Record<string, string>>
    priority: number
    attempts: number
    failedAt: number
    failure: string
    payloadBytes: number
}

export interface DeadLetterPage {
    entries: DeadLetterEntry[]
    /** Pass as `after` to continue. Absent means the listing is complete. */
    next?: string
}

export type AdminMutationResult = { status: 'ok' } | { status: 'not-found' }

/**
 * The typed internal protocol the public wrapper drives. Everything a queue can be asked, so an
 * in-process caller and a remote proxy are the same shape - which is what lets the conformance
 * suite run over both.
 */
export interface WorkQueueProtocol<TTask> {
    enqueue(request: EnqueueRequest<TTask>): Promise<EnqueueResult>
    acquire(request: AcquireRequest): Promise<AcquireResult<TTask>>
    complete(request: CompleteRequest): Promise<LeaseMutationResult>
    fail(request: FailRequest): Promise<LeaseMutationResult>
    renew(request: RenewRequest): Promise<LeaseMutationResult>
    stats(): Promise<WorkQueueSnapshot>
    listDeadLetters(options?: PageOptions): Promise<DeadLetterPage>
    retryDeadLetter(taskId: string): Promise<AdminMutationResult>
    discardDeadLetter(taskId: string): Promise<AdminMutationResult>
}
